FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
WORKDIR "/src/admin/host/Berry.Spider.Admin.HttpApi.Host"
#RUN dotnet build "Berry.Spider.Admin.HttpApi.Host.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Berry.Spider.Admin.HttpApi.Host.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_HTTP_PORTS=80 ASPNETCORE_ENVIRONMENT=PROD
ADD deploy/app_start.sh /app/start.sh
CMD ["sh","/app/start.sh","80","dotnet Berry.Spider.Admin.HttpApi.Host.dll","PROD"]