FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY  . .
RUN dotnet restore "host/Berry.Spider.HttpApi.Host/Berry.Spider.HttpApi.Host.csproj"
COPY . .
WORKDIR "/src/Berry.Spider.HttpApi.Host"
RUN dotnet build "Berry.Spider.HttpApi.Host.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Berry.Spider.HttpApi.Host.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Berry.Spider.HttpApi.Host.dll"]