// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Berry.Spider.OpenAI.Contracts;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Berry.Spider.OpenAI;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISpiderOpenAIAppService), typeof(SpiderOpenAIClientProxy))]
public partial class SpiderOpenAIClientProxy : ClientProxyBase<ISpiderOpenAIAppService>, ISpiderOpenAIAppService
{
    public virtual async Task<TextGenerationDto> TextGenerationAsync(TextGenerationInput input)
    {
        return await RequestAsync<TextGenerationDto>(nameof(TextGenerationAsync), new ClientProxyRequestTypeValue
        {
            { typeof(TextGenerationInput), input }
        });
    }
}
