//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berry.Spider.NaiPan.weiyuanchuang
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.naipan.com/", ConfigurationName="Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuangPortType")]
    public interface weiyuanchuangPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weiyuanchuang", ReplyAction="urn:weiyuanchuangResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuangResponse weiyuanchuang(Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuangRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weiyuanchuang", ReplyAction="urn:weiyuanchuangResponse")]
        System.Threading.Tasks.Task<Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuangResponse> weiyuanchuangAsync(Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuangRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weiyuanchuang_zimeiti", ReplyAction="urn:weiyuanchuang_zimeitiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuang_zimeitiResponse weiyuanchuang_zimeiti(Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuang_zimeitiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weiyuanchuang_zimeiti", ReplyAction="urn:weiyuanchuang_zimeitiResponse")]
        System.Threading.Tasks.Task<Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuang_zimeitiResponse> weiyuanchuang_zimeitiAsync(Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuang_zimeitiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:AIWeiTo", ReplyAction="urn:AIWeiToResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Berry.Spider.NaiPan.weiyuanchuang.AIWeiToResponse AIWeiTo(Berry.Spider.NaiPan.weiyuanchuang.AIWeiToRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:AIWeiTo", ReplyAction="urn:AIWeiToResponse")]
        System.Threading.Tasks.Task<Berry.Spider.NaiPan.weiyuanchuang.AIWeiToResponse> AIWeiToAsync(Berry.Spider.NaiPan.weiyuanchuang.AIWeiToRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:toInsertUserAddContent", ReplyAction="urn:toInsertUserAddContentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Berry.Spider.NaiPan.weiyuanchuang.toInsertUserAddContentResponse toInsertUserAddContent(Berry.Spider.NaiPan.weiyuanchuang.toInsertUserAddContentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:toInsertUserAddContent", ReplyAction="urn:toInsertUserAddContentResponse")]
        System.Threading.Tasks.Task<Berry.Spider.NaiPan.weiyuanchuang.toInsertUserAddContentResponse> toInsertUserAddContentAsync(Berry.Spider.NaiPan.weiyuanchuang.toInsertUserAddContentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:replaceHtml_new", ReplyAction="urn:replaceHtml_newResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Berry.Spider.NaiPan.weiyuanchuang.replaceHtml_newResponse replaceHtml_new(Berry.Spider.NaiPan.weiyuanchuang.replaceHtml_newRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:replaceHtml_new", ReplyAction="urn:replaceHtml_newResponse")]
        System.Threading.Tasks.Task<Berry.Spider.NaiPan.weiyuanchuang.replaceHtml_newResponse> replaceHtml_newAsync(Berry.Spider.NaiPan.weiyuanchuang.replaceHtml_newRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="weiyuanchuang", WrapperNamespace="http://www.naipan.com/", IsWrapped=true)]
    public partial class weiyuanchuangRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.naipan.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string regname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.naipan.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string regsn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.naipan.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string content;
        
        public weiyuanchuangRequest()
        {
        }
        
        public weiyuanchuangRequest(string regname, string regsn, string content)
        {
            this.regname = regname;
            this.regsn = regsn;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="weiyuanchuangResponse", WrapperNamespace="http://www.naipan.com/", IsWrapped=true)]
    public partial class weiyuanchuangResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.naipan.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public weiyuanchuangResponse()
        {
        }
        
        public weiyuanchuangResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="weiyuanchuang_zimeiti", WrapperNamespace="http://www.naipan.com/", IsWrapped=true)]
    public partial class weiyuanchuang_zimeitiRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.naipan.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string regname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.naipan.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string regsn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.naipan.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.naipan.com/", Order=3)]
        public int srctype;
        
        public weiyuanchuang_zimeitiRequest()
        {
        }
        
        public weiyuanchuang_zimeitiRequest(string regname, string regsn, string content, int srctype)
        {
            this.regname = regname;
            this.regsn = regsn;
            this.content = content;
            this.srctype = srctype;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="weiyuanchuang_zimeitiResponse", WrapperNamespace="http://www.naipan.com/", IsWrapped=true)]
    public partial class weiyuanchuang_zimeitiResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.naipan.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public weiyuanchuang_zimeitiResponse()
        {
        }
        
        public weiyuanchuang_zimeitiResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AIWeiTo", WrapperNamespace="http://www.naipan.com/", IsWrapped=true)]
    public partial class AIWeiToRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.naipan.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string webContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.naipan.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string regname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.naipan.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string used_ip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.naipan.com/", Order=3)]
        public int srctype;
        
        public AIWeiToRequest()
        {
        }
        
        public AIWeiToRequest(string webContent, string regname, string used_ip, int srctype)
        {
            this.webContent = webContent;
            this.regname = regname;
            this.used_ip = used_ip;
            this.srctype = srctype;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AIWeiToResponse", WrapperNamespace="http://www.naipan.com/", IsWrapped=true)]
    public partial class AIWeiToResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.naipan.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public AIWeiToResponse()
        {
        }
        
        public AIWeiToResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="toInsertUserAddContent", WrapperNamespace="http://www.naipan.com/", IsWrapped=true)]
    public partial class toInsertUserAddContentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.naipan.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string resultStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.naipan.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string regname;
        
        public toInsertUserAddContentRequest()
        {
        }
        
        public toInsertUserAddContentRequest(string resultStr, string regname)
        {
            this.resultStr = resultStr;
            this.regname = regname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="toInsertUserAddContentResponse", WrapperNamespace="http://www.naipan.com/", IsWrapped=true)]
    public partial class toInsertUserAddContentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.naipan.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public toInsertUserAddContentResponse()
        {
        }
        
        public toInsertUserAddContentResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="replaceHtml_new", WrapperNamespace="http://www.naipan.com/", IsWrapped=true)]
    public partial class replaceHtml_newRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.naipan.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string html;
        
        public replaceHtml_newRequest()
        {
        }
        
        public replaceHtml_newRequest(string html)
        {
            this.html = html;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="replaceHtml_newResponse", WrapperNamespace="http://www.naipan.com/", IsWrapped=true)]
    public partial class replaceHtml_newResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.naipan.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public replaceHtml_newResponse()
        {
        }
        
        public replaceHtml_newResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface weiyuanchuangPortTypeChannel : Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuangPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class weiyuanchuangPortTypeClient : System.ServiceModel.ClientBase<Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuangPortType>, Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuangPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public weiyuanchuangPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(weiyuanchuangPortTypeClient.GetBindingForEndpoint(endpointConfiguration), weiyuanchuangPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public weiyuanchuangPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(weiyuanchuangPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public weiyuanchuangPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(weiyuanchuangPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public weiyuanchuangPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuangResponse weiyuanchuang(Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuangRequest request)
        {
            return base.Channel.weiyuanchuang(request);
        }
        
        public System.Threading.Tasks.Task<Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuangResponse> weiyuanchuangAsync(Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuangRequest request)
        {
            return base.Channel.weiyuanchuangAsync(request);
        }
        
        public Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuang_zimeitiResponse weiyuanchuang_zimeiti(Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuang_zimeitiRequest request)
        {
            return base.Channel.weiyuanchuang_zimeiti(request);
        }
        
        public System.Threading.Tasks.Task<Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuang_zimeitiResponse> weiyuanchuang_zimeitiAsync(Berry.Spider.NaiPan.weiyuanchuang.weiyuanchuang_zimeitiRequest request)
        {
            return base.Channel.weiyuanchuang_zimeitiAsync(request);
        }
        
        public Berry.Spider.NaiPan.weiyuanchuang.AIWeiToResponse AIWeiTo(Berry.Spider.NaiPan.weiyuanchuang.AIWeiToRequest request)
        {
            return base.Channel.AIWeiTo(request);
        }
        
        public System.Threading.Tasks.Task<Berry.Spider.NaiPan.weiyuanchuang.AIWeiToResponse> AIWeiToAsync(Berry.Spider.NaiPan.weiyuanchuang.AIWeiToRequest request)
        {
            return base.Channel.AIWeiToAsync(request);
        }
        
        public Berry.Spider.NaiPan.weiyuanchuang.toInsertUserAddContentResponse toInsertUserAddContent(Berry.Spider.NaiPan.weiyuanchuang.toInsertUserAddContentRequest request)
        {
            return base.Channel.toInsertUserAddContent(request);
        }
        
        public System.Threading.Tasks.Task<Berry.Spider.NaiPan.weiyuanchuang.toInsertUserAddContentResponse> toInsertUserAddContentAsync(Berry.Spider.NaiPan.weiyuanchuang.toInsertUserAddContentRequest request)
        {
            return base.Channel.toInsertUserAddContentAsync(request);
        }
        
        public Berry.Spider.NaiPan.weiyuanchuang.replaceHtml_newResponse replaceHtml_new(Berry.Spider.NaiPan.weiyuanchuang.replaceHtml_newRequest request)
        {
            return base.Channel.replaceHtml_new(request);
        }
        
        public System.Threading.Tasks.Task<Berry.Spider.NaiPan.weiyuanchuang.replaceHtml_newResponse> replaceHtml_newAsync(Berry.Spider.NaiPan.weiyuanchuang.replaceHtml_newRequest request)
        {
            return base.Channel.replaceHtml_newAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.weiyuanchuangHttpSoap11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.weiyuanchuangHttpSoap12Endpoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.weiyuanchuangHttpSoap11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://www.naipan.com/api/weiyuanchuang.weiyuanchuangHttpSoap11Endpoint/");
            }
            if ((endpointConfiguration == EndpointConfiguration.weiyuanchuangHttpSoap12Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://www.naipan.com/api/weiyuanchuang.weiyuanchuangHttpSoap12Endpoint/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            weiyuanchuangHttpSoap11Endpoint,
            
            weiyuanchuangHttpSoap12Endpoint,
        }
    }
}
