// <auto-generated />
using System;
using Berry.Spider.EntityFrameworkCore.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace Berry.Spider.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(SpiderDbContext))]
    partial class SpiderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.MySql)
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Berry.Spider.Domain.TouTiao.TouTiaoSpiderContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("longtext")
                        .HasColumnName("作者");

                    b.Property<int>("Collected")
                        .HasColumnType("int")
                        .HasColumnName("已采");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("内容");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("longtext")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("出处");

                    b.Property<string>("Keywords")
                        .HasColumnType("longtext")
                        .HasColumnName("关键字");

                    b.Property<string>("PageUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("PageUrl");

                    b.Property<int>("Published")
                        .HasColumnType("int")
                        .HasColumnName("已发");

                    b.Property<string>("Tag")
                        .HasColumnType("longtext")
                        .HasColumnName("tag");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("时间");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("标题");

                    b.HasKey("Id");

                    b.ToTable("Content", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
