// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Berry.Spider.Biz;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Berry.Spider.Biz;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISpiderAppInfoService), typeof(SpiderAppInfoClientProxy))]
public partial class SpiderAppInfoClientProxy : ClientProxyBase<ISpiderAppInfoService>, ISpiderAppInfoService
{
    public virtual async Task<List<SpiderAppInfoDto>> GetSpiderAppListAsync(int top)
    {
        return await RequestAsync<List<SpiderAppInfoDto>>(nameof(GetSpiderAppListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(int), top }
        });
    }

    public virtual async Task<SpiderAppInfoDto> GetSpiderAppInfoAsync(string bizNo)
    {
        return await RequestAsync<SpiderAppInfoDto>(nameof(GetSpiderAppInfoAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), bizNo }
        });
    }
}
