// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Berry.Spider.Core;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Berry.Spider.Core;

public class CustomPagedResultRequestDto
{
    public int Page { get; set; }

    public int PageSize { get; set; }
}
