// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Berry.Spider.Core;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Berry.Spider.Core;

public enum MachineStatus
{
    None = 0,
    Online = 10,
    Offline = 20
}
