// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Berry.Spider.Core;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Berry.Spider.Core;

public enum SpiderSourceFrom
{
    Text_File_Import = 10,
    Excel_File_Import = 20,
    Json_File_Import = 30,
    TouTiao_Information = 101,
    TouTiao_Information_Composition = 102,
    TouTiao_Question = 110,
    TouTiao_HighQuality_Question = 111,
    Baidu_Related_Search = 201,
    Sogou_Related_Search = 301,
    Sogou_WenWen = 401,
    TouTiao_Question_Ext_NO_1 = 2110,
    TouTiao_HighQuality_Question_Ext_NO_1 = 2111
}
