// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Berry.Spider.Biz;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Berry.Spider.Biz;

public class ServMachineOnlineDto
{
    public string MachineName { get; set; }

    public string MachineCode { get; set; }

    public string MachineIpAddr { get; set; }

    public string MachineMacAddr { get; set; }

    public string ConnectionId { get; set; }
}
