FROM mcr.microsoft.com/dotnet/runtime:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["src/Berry.Spider.Consumers/Berry.Spider.Consumers.csproj", "src/Berry.Spider.Consumers/"]
RUN dotnet restore "src/Berry.Spider.Consumers/Berry.Spider.Consumers.csproj"
COPY . .
WORKDIR "/src/src/Berry.Spider.Consumers"
RUN dotnet build "Berry.Spider.Consumers.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Berry.Spider.Consumers.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Berry.Spider.Consumers.dll"]
