// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Berry.Spider;
using Berry.Spider.Core;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Berry.Spider;

public class PushFromFileBasicDto
{
    public SpiderSourceFrom SourceFrom { get; set; }

    public IFormFile File { get; set; }

    public string TraceCode { get; set; }
}
