// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Berry.Spider;
using Berry.Spider.Core;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Berry.Spider;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISpiderPubAndRecAppService), typeof(SpiderPubAndRecClientProxy))]
public partial class SpiderPubAndRecClientProxy : ClientProxyBase<ISpiderPubAndRecAppService>, ISpiderPubAndRecAppService
{
    public virtual async Task ClearTodoTaskAsync(SpiderSourceFrom from)
    {
        await RequestAsync(nameof(ClearTodoTaskAsync), new ClientProxyRequestTypeValue
        {
            { typeof(SpiderSourceFrom), from }
        });
    }
}
