// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Berry.Spider.Common;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Berry.Spider.Common;

public class DeDuplicationTxtFile
{
    public IFormFile File { get; set; }
}
